#!/usr/bin/env -S ansible-playbook -i localhost, -t noop
---
- name: Install and Configure Localhost
  hosts: "{{ target_hosts | default('localhost') }}"
  connection: "{{ target_connection | default('local') }}"
  become: yes
  become_user: "{{ target_user | default(lookup('env', 'USER')) }}"
  vars:
    ansible_pipelining: true
    allow_world_readable_tmpfiles: true

    # Create hard dirs in ~/.config so that multiple sources can link into the dir
    # If there are softlinks from multiple sources the softlinks will end up in the config repo
    config_path: "{{ ansible_user_dir }}/.config"
    content_directories:
      - "{{ config_path }}/git"
      - "{{ config_path }}/nvim"
      - "{{ config_path }}/tmuxinator"
    # TODO: Add a second stow to loop on which has packages without the leading .config
    # and have the dest be ansbile_user_dir/.config
    # TODO: Fix the packages failing b/c stow doesn't own the dir
    stow:
      - src: "{{ playbook_dir }}/dotfiles"
        dest: "{{ ansible_user_dir }}"
          # packages: [bash, git, nvim, tmux, tmuxinator, zsh]
        packages: [bash, git, zsh]

  tasks:
    - name: Set user shell to zsh
      ansible.builtin.user:
        name: "{{ target_user | default(lookup('env', 'USER')) }}"
        shell: /bin/zsh
      become: yes
      become_user: root
      tags: [user-install]

    - name: Configure Tmux Plugins
      ansible.builtin.include_role:
        name: rjayroach.common.tmux
      tags: [user-install]

    - name: Configure Tmux Plugins
      ansible.builtin.include_role:
        name: rjayroach.common.content
      tags: [user-install]
