---
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
ungrouped:
  hosts:
    localhost:
  vars:
    mods:
      tmux:
      # docker:
      # neovim:
      # zsh:
      #   omz_path: ~/.local/share
      # ruby:
