---
- ansible.builtin.stat:
    path: "packages/{{ package }}/vars.yml"
  register: vars_file
  tags: [always]

- ansible.builtin.include_vars:
    file: "packages/{{ package }}/vars.yml"
    name: _vars
  when: vars_file.stat.exists
  tags: [always]

- ansible.builtin.debug:
    var: _vars
  when: vars_file.stat.exists
  tags: [debug]

- ansible.builtin.set_fact:
    packages: "{{ packages | combine({package: _vars}, recursive=True) }}"
  when: vars_file.stat.exists
  tags: [always]

# - ansible.builtin.fail:
#     msg: "{{ package }}/vars.yml not found"
#   ignore_errors: yes
#   when: not vars_file.stat.exists
#   tags: [never]

- ansible.builtin.stat:
    path: "packages/{{ package }}/tasks.yml"
  register: tasks_file
  tags: [user-admin]

- ansible.builtin.include_tasks:
    file: "packages/{{ package }}/tasks.yml"
  when: tasks_file.stat.exists
  tags: [user-admin]

# - fail:
#     msg: "{{ package }}/tasks.yml"
#   when: not tasks_file.stat.exists
#   tags: [user-config]
