---
ventoy:
  version: v1.1.07
  dir: ventoy-1.1.07
  file: ventoy-1.1.07-linux.tar.gz
  checksum: sha256:4ffabce468b03d6357ce5f4594e209714d1509d065da102938096dad6654c36e
iso_files:
- name: debian-13.1.0-amd64-netinst.iso
  url: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.1.0-amd64-netinst.iso
- name: proxmox-ve_9.0-1.iso
  url: https://enterprise.proxmox.com/iso/proxmox-ve_9.0-1.iso
